---
# this file  it's for our configuration for github action

# این نام در گیت هاب نمایش داده می شود
name: Checks

# مشخص کردن اکشن (trigger)
on: [push]

jobs:
    testlint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Loging to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              run: docker-compose exces --rm app sh -c 'python manage.py test'
            - name: Lint
              run: docker-compose run --rm app sh -c 'flake8'
